[profile.default]
solc = "0.8.28"
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "forge-cache"
viaIR = true
evm_version = "shanghai"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

ffi = true
ast = true
build_info = true
extra_output = ['storageLayout', 'evm.gasEstimates']
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"

[fmt] # See https://book.getfoundry.sh/reference/config/formatter
single_line_statement_blocks = "multi"
multiline_func_header = "all"
contract_new_lines = true
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
wrap_comments = true
ignore = ['./script/**/*']